### ISSUE TITLE
Creator: Reduce redundant tasks through templates

### ISSUE THREAD

**Issue by brettfiedler** [phetsims/paper-land#161]
We're seeing that there are some common "forms" that a paper takes depending on what you want to do (e.g., make an image and make it follow the paper). We could reduce the amount of work needed to create these papers by creating Paper templates for common papers (e.g., Image Component -> Position Component -> Paper Movement Controller)

Maybe we hijack the Code Snippets database for this since we're not focusing there anymore?

Here's a first guess at what might work:

HOW TO USE TEMPLATE:
- Put some space in the right hand area when no paper is selected. Should this be a dropdown or something more complex? I think in an ideal world it would be something we could select from the right and drag'n'drop into the left-hand area.
- If a program with existing components exist, let's just automatically add a suffix: "Copy", "Copy1", "Copy2" which I think is fairly common.

HOW TO CREATE NEW TEMPLATE:
- Create a new button in a paper's meta form that allows you to "Create as New Template" and lock access to the button behind our usual method.
  - For some measure of safety, let's have the button create a prompt to enter the title of the Template so we don't accidentally overwrite things.

**Comment by jessegreenberg** [comment]
Some discussion today:

We want to improve template creation. Users should be able to add their own templates, and collect unique templates in each space. That means we need to flesh out the UI for making templates and also add templates to the database.

**Comment by jessegreenberg** [comment]
This is complete and I think ready for review. I posted some example images to the slack channel.

There are potential usability problems that we may want to address.

1) The "Edit Templates" form can be seen when you are not editing another program or component. If you modify a program or component while part way through editing template metadata you will lose your progress,
2) To start editing an existing template you have to delete all programs or go to a new project. When you load a template it has to replace all programs in the current project because the template is saved from all programs in the current project. This makes the flow inconvenient sometimes, for example:
  a)  Make a few programs for your template
  b) Start creating a new template from your programs, get all the way to "Add Template to Space".
  c) Find that the name you wanted to use for the template is already taken. Now you have to either
    - delete all your programs so you can edit the existing template with that name or
    - save the project, create a new empty one, delete the existing template, go back to original project, re-enter template metadata, and save

It is possible these issues are minor but I hit them pretty quickly while testing the feature. But possibly because I was using the same name for my tests.

Assigning to @brettfiedler to test and next steps!

**Comment by jessegreenberg** [comment]
Honestly, the UX is too painful to use this 🤣. Any time you try to edit template programs it deletes your metadata. Ill improve it a bit.

**Comment by jessegreenberg** [comment]
I think this can be improved by 
1) Making it so that the Edit Templates form is always available so that you can edit programs while making a new template.
2) Templates are uniquely identified by an ID in the DB. We should allow multiple templates with the same name. Then you won't run into problem 2 at https://github.com/phetsims/paper-land/issues/161#issuecomment-1791691694.

**Comment by jessegreenberg** [comment]
These were done in the dev branch, I will test a bit more before merging into main.

**Comment by jessegreenberg** [comment]
These changes were merged into main with other fixes.

**Comment by brettfiedler** [comment]
Found issues when TS worked on TacTiles project, but they have been cleared up. Looking good!
