### ISSUE TITLE
Creator: Arrows exit right on outputs, enter left on inputs

### ISSUE THREAD

**Issue by brettfiedler** [phetsims/paper-land#163]
This was brought up at design meeting recently. 

One idea to clean up some of the view of Creator is to have the ends of the arrows exit the right of the papers and arrows coming in enter the left side.

**Comment by jessegreenberg** [comment]
On the dev branch there are output circles that feed into input circles. But it looks a bit confusing now because lines occlude much of the interface. Ill try out a different drawing algorithm and see if it looks better before reassigning for review.

**Comment by jessegreenberg** [comment]
Here is a new way of organizing them that might be easier to read.

![image](https://github.com/user-attachments/assets/c9f1bc0b-1f89-43e9-b468-c7cef2c9478e)

It works like this:

If the output.x is less than the input.x, just draw a straight line from output to input.
Else, create a zig-zag that wires between the listed components. The horizontal offset to the left of the input circle is a function of the Y value of the start position. This makes it so that the lines don't overlap and become impossible to read. However, this lazy approach makes it so the offset grows/shrinks as you drag programs up and down which is a little strange. But the drawing code for connections has no knowledge of which program the point is on. We can definitely improve it but I didn't want to spend more time before discussing with @brettfiedler.

@brettfiedler ready for your review and thoughts.

**Comment by brettfiedler** [comment]
Really cool! I like it a lot overall and definitely cleans up the  I did find one potentially buggy behavior. Video attached. The X offset for the lines seem to depend on the Y position. I think we'd probably want to avoid the lines completely collapsing into the edge of the paper.

https://github.com/user-attachments/assets/3f7944bb-d88e-4824-99af-70acbf05135e

**Comment by jessegreenberg** [comment]
Totally right, the offset is tied to Y position and the reason for that lazy approach is described in https://github.com/phetsims/paper-land/issues/163#issuecomment-2329969963. Ill work on improving it a bit.

**Comment by brettfiedler** [comment]
Ah yes, you did say that, I see now, sorry! I think in general that might be helpful to set the offset yourself (though I suspect most paper positions are organic and not purposeful). But perhaps we should avoid completely collapsing them and add a minimum offset?

**Comment by jessegreenberg** [comment]
OK great, that would be a very easy fix. If I can't get it working better in ~15 minutes, Ill go with increasing the offset.

**Comment by jessegreenberg** [comment]
OK the offset for a wire is now relative to the origin of the program holding the output connection. So there is always some offset and the offsets don't change as you drag the program vertically.

How is this @brettfiedler, what other changes should we make?

**Comment by brettfiedler** [comment]
I think we're good. And I like that the offset decreases to the minimum when we collapse the programs. All good here!
