### ISSUE TITLE
Add visible Bounds to Camera and Display (board)

### ISSUE THREAD

**Issue by brettfiedler** [phetsims/paper-land#167]
Suggestion from codesigner:

When we create Bounds, it's difficult to tell where they are set physically. Since this is a physical Paper event we are creating, we should make sure it's possible to view them in Camera (like we do with Whiskers) and be able to project them easily into the projected space in Display.

(MAYBE) For Camera, let's add another box like the Whiskers box to draw any detected Bounds (if none and we need to draw something, just assume the bounds are the red box?)

(DEFINITELY) To display them in Display, we'll probably just want to edit the Creator form for Bounds and add a "Make Bounds Visible?" checkbox when setting up the bounds. This should probably come with a field to assign a default color and line width for the created bounds.

**Comment by jessegreenberg** [comment]
> edit the Creator form for Bounds and add a "Make Bounds Visible?" checkbox when setting up the bounds.

If we do this it will be the first "view" component that is automatically coupled with a model component. IMO that could be confusing for Creator. It is now trivial to draw rectangles around the bounds because the Rectangle view component has this function:

![image](https://github.com/phetsims/paper-land/assets/6396244/7249d3dd-1bdb-4147-8024-b2a3fc7f5b44)

I also created a template so you can easily create a bounds model with a rectangle view:
![image](https://github.com/phetsims/paper-land/assets/6396244/b006d49a-7aa9-4a48-ba83-599b4e92b8b2)

@brettfiedler are you OK with this?

**Comment by brettfiedler** [comment]
I'm okay with this and the existence of Templates helps a lot. Closing unless it's communicated by others this isn't enough.
