### ISSUE TITLE
Get lint running

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/paper-land#22]
We would like lint to work in this repo. There is some lint support form the original project, but when we tried to run it it didn't work. We could figure out why. But even better, we should see if we can use PhET's lint rules in this repo.

**Comment by BLFiedler** [comment]
JB indicated he wanted to work on this, so elevating the priority.

**Comment by BLFiedler** [comment]
We confirmed synchronously that the work completed yesterday passes on my machine after a `npm update` and `npm run lint`. More work to align with part of PhET's config happening now.

**Comment by jbphet** [comment]
As @BLFiedler noted above, we have a working and reasonably useful lint setup working.  I set this up independently of the PhET lint configuration because I did a quick check with the PhET config, and there were tons of fails.  However, after giving it more thought, it's worth a bit more investment of time to make the PhET configuration work and just disable a bunch of the rules that the legacy code won't pass, and to clean up the legacy code to work with some of the rules that I don't want to disable.  This will make the code in this repo more consistent with PhET's standards and will also work better with the IDE setups.  I'll invest an hour or tow in this and see where I get.

**Comment by jbphet** [comment]
I was able to get the PhET setup for ESLint working.  I touched a lot of code while doing this, so we will need to keep an eye out for any unintended consequences.

This should put us in a position where other developers can jump in more easily, since the code will look stylistically similar to what they are used to.  It should also help us to avoid bugs while extending this.
