### ISSUE TITLE
Populate the database with templates and examples

### ISSUE THREAD

**Issue by brettfiedler** [phetsims/paper-land#46]
We'd like to start creating as many general templates as we can to make it easier to find reusable Programs and have something for designers to pull from. This post contains a list of general templates we would like to create in the `templates` playspace. 

Please recommend additional Programs in this issue and they will be added to the top post (this one). If you have access, you may also directly edit this post. Mark off templates that have been created.

- [x] Create Dial mapped to paper rotation
- [x] Create Radio Button
- [x] Create Slider with value mapped to paper position
  - [ ] And rotation
- [ ] Use mouse click event to make something happen
  - [ ] Mouse down
  - [ ] Mouse up
  - [ ] Use mouse position to make something happen
- [ ] Use keypress event to make something happen
  - [ ] Key down
  - [ ] Key Up
- [x] Create a model Property
- [x] Link to a model Property
- [x] Play sound (complete)
  - [x] Play looping sound
  - [x] Play sound in response to new value (e.g., from model Property)
- [x] Play TTS
  - [x] Play TTS in response to new value (e.g., from model Property)
- [x] Create Image
  - [x] Animate Image
- [x] View code for a slider that allows for Qualitative values
    - Specifically, wondering how a designer can design and test parameters for a slider. 

Some more from 3/7/23:
- [x] Properties that implement linear, exponential, and other changes. Directly controlled by paper position.
- [ ] Description mappers (value -> string, enumeration -> string, bool -> string)

**Comment by terracoda** [comment]
@jessegreenberg and @terracoda spent 2.5 hours creating a few templates and a few snippets and then trying to use them.

We created 3 templates:
- Model Template
- View Template
- Slider Template

To help fill in the templates, we created at least 2 snippets:
- a NumberProperty that could be used to create model properties for Voltage and Resistance
- a DerivedProperty to calculate Current from Voltage and Resistance
- Note each snippet contains code blocks to put under "onProgramAdded" and "onProgramRemoved"

We ran into trouble when we tried to use the templates to recreate the Ohm's Law sliders that we already created.
A typo in the resistance property was one issue we were able to resolve. Unfortunately, there is something else that is not throwing an error that is not working. @jessegreenberg will take a deeper look into the templates to see what the problem is.

**Comment by jessegreenberg** [comment]
I got the template we were working on today working. There was a small problem with how we were positioning our slider. I created a few more examples (in jg-tests space for now), and some more snippets (Voicing, Checkbox, link)

**Comment by BLFiedler** [comment]
Working on templates has lead us to believe that we should focus on examples instead of open-ended templates. I want to convert this list into keywords we can search for and find places in examples to implement the above desired "templates".

Self-assigning for now to complete and close in favor of specific issues for examples.

**Comment by brettfiedler** [comment]
We've moved away from templates and examples and have focused on a component interface. Closing.
