### ISSUE TITLE
Update implementation-notes.md

### ISSUE THREAD

**Issue by brettfiedler** [phetsims/paper-land#75]
The tool has changed a lot since https://github.com/phetsims/paper-land/blob/master/docs/use/implementation-notes.md was created. Let's update it to cover all of the structure and capabilities we've introduced specific to creating programs and interacting with it on the Board.

**Comment by jessegreenberg** [comment]
OK, updated the example code to use current functions.

> What are your thoughts on keeping this focused

Yea, that makes sense to me! I'd probably keep the MVC summary separate and move out of implementation-notes (because it isn't about the implementation of paper-land). Then we could have a `board-api.md` for all of the functions related to the board (onProgramAdded/addModelPropertyLink/addModelComponent, all the logging functions, marker stuff, everything else). It could point to the model-view-controller summary and encourage reading it.

If that sounds good, reassign and I can write it up!

**Comment by BLFiedler** [comment]
Sounds good! Sounds like we have 3 potential docs?


Board Implementation.md
Board API.md
MVC Framework Summary

**Comment by jessegreenberg** [comment]
I started https://github.com/phetsims/paper-land/blob/master/docs/use/board-api.md, but there is quite a bit more to add and reformat.

**Comment by brettfiedler** [comment]
Structure here is good as is! We'll need to revisit with continued capability updates, but if that falls off we'll create a new issue.
