### ISSUE TITLE
Add support for markers in the paper programs and the design board

### ISSUE THREAD

**Issue by jbphet** [phetsims/paper-land#86]
We've been adding support for using "markers", which are circles that are a bit bigger than the one used to identify the paper programs. I don't see an issue for this and have a commit to make, so I'm adding this.  @jessegreenberg - Let me know if there is one already and I just missed it.

**Comment by jessegreenberg** [comment]
Thanks, this is great. Here is the branch issue: https://github.com/phetsims/paper-land/issues/83. We also had #67, but this can be a continuation.

**Comment by jessegreenberg** [comment]
I merged the changes into master and tested them out for a bit. Everything is working great @jbphet, nicely done on this!

I made a couple of programs that exercise the new emitters. I think the next step is to discuss the examples and API with the team to confirm that what we are hoping for is covered. But otherwise I think this is done.

**Comment by brettfiedler** [comment]
This is indeed done and proven to work very well for virtual and real papers. Noting that there is a set factor for a dot to be considered a marker. This is set at calibration when the average dot size is determined.
